#!/usr/bin/env python3

import os
import sys
import nltk
from analyzer import Analyzer
from termcolor import colored
from helpers import *

def main():
    # Ensure Proper Usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    # get tweets
    tweet_bank = get_user_timeline(sys.argv[1])
    if(tweet_bank==None):
        sys.exit("Could not retrive {}'s tweets".format(sys.argv[1]))
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    
    # analyze tweets
    for i in tweet_bank:
        score = analyzer.analyze(i)
        
        tweet_s = str(score) + "\t" + i
        if score > 0.0:
            print(colored(tweet_s, "green"))
        elif score < 0.0:
            print(colored(tweet_s, "red"))
        else:
            print(colored(tweet_s, "yellow"))
    
    
if __name__== "__main__":
    main()